name: Build and test

on:
  schedule:
    - cron: "0 19 * * *" # run at 4 AM JST
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: osrf/ros:foxy-desktop

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Clone dependency packages
        run: |
          mkdir dependency_ws
          vcs import dependency_ws < build_depends.repos
          apt-get -y update
          rosdep update
          rosdep install -y --from-paths . --ignore-src --rosdistro foxy

      - name: Build
        run: |
          . /opt/ros/foxy/setup.sh
          colcon build --event-handlers console_cohesion+ \
            --cmake-args -DCMAKE_BUILD_TYPE=Release

      - name: Run tests
        run: |
          . /opt/ros/foxy/setup.sh
          colcon test \
            --event-handlers console_cohesion+ \
            --return-code-on-test-failure
