name: Check spelling

on:
  pull_request:
    branches:
      - main

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: streetsidesoftware/cspell-action@v1.1.1
        with:
          config: ".github/workflows/.cspell.json"
